<?php


declare(strict_types=1);

// just write a paragraph that confirms this file is working


/**
 * =============================================================================
 * public/index.php — Front Controller
 * =============================================================================
 *
 * WHAT IS A FRONT CONTROLLER?
 * Every HTTP request to the app enters through this single file.
 * Apache's .htaccess rewrites all URLs here.
 *
 * WHY ONE ENTRY POINT?
 * - Security headers, auth, logging — you write them once here, they apply
 *   to every request automatically.
 * - Keeps PHP files out of the browser's direct reach. Nothing in src/ or
 *   config/ is accessible via URL — only what's in public/ is visible.
 * - Clean URLs: /login instead of /login.php
 *
 * BOOT SEQUENCE (order matters — each step depends on the previous):
 *   1. Autoloader   — makes all classes findable without require_once
 *   2. .env         — populates $_ENV with secrets
 *   3. Config       — reads $_ENV into a typed PHP array
 *   4. Error mode   — show errors in dev, hide them in prod
 *   5. HTTP headers — sent on every response, before any output
 *   6. Database     — configured (connection not opened yet — lazy)
 *   7. Session      — started (added in Step 2 of this series)
 *   8. Routes       — registered
 *   9. Dispatch     — current request matched and executed
 * =============================================================================
 */

// =============================================================================
// 1. Autoloader
// =============================================================================
// vendor/autoload.php is generated by Composer. It knows how to find any
// class under the CourseCompanion\ namespace because composer.json declares:
//   "autoload": { "psr-4": { "CourseCompanion\\": "src/" } }
//
// PSR-4 rule: CourseCompanion\Core\Database → src/Core/Database.php
// You never write require_once for individual classes. Composer handles it.

if (!file_exists(__DIR__ . '/../vendor/autoload.php')) {
    http_response_code(500);
    die('Dependencies not installed. Run: composer install');
}

require_once __DIR__ . '/../vendor/autoload.php';

// Now classes are autoloadable. Declare use statements AFTER the autoloader.
use CourseCompanion\Core\Database;
use CourseCompanion\Core\Router;
use CourseCompanion\Core\Session;     // ← uncomment in Step 2
// use CourseCompanion\Middleware\AuthMiddleware;   // ← uncomment in Step 3
// use CourseCompanion\Middleware\GuestMiddleware;  // ← uncomment in Step 3

// =============================================================================
// 2. Environment Variables
// =============================================================================
// phpdotenv reads .env and populates $_ENV.
// createImmutable() = once loaded, values can't be overwritten at runtime.
// This means even if an attacker somehow injects HTTP headers that look like
// env vars, your DB password can't be replaced mid-request.
//
// ->required([...]) throws an exception immediately if a key is missing,
// instead of failing silently later. Fail fast = easier to debug.

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__ . '/../');
$dotenv->load();
$dotenv->required([
    'APP_SECRET',
    'DB_HOST', 'DB_PORT', 'DB_NAME', 'DB_USER',
]);

// =============================================================================
// 3. Application Config
// =============================================================================
// config/app.php returns a PHP array. We assign it to $config.
// All code below this point reads from $config, never directly from $_ENV.
// This means the rest of the app doesn't need to know where config came from.

$config = require __DIR__ . '/../config/app.php';

// =============================================================================
// 4. Error Reporting
// =============================================================================
// APP_DEBUG=true  in .env → show all errors in browser (development)
// APP_DEBUG=false in .env → log errors, show nothing (production)
//
// NEVER show errors in production! PHP error messages can reveal:
// - Absolute file paths (attacker learns your server layout)
// - Variable names and values (potential secret leaking)
// - Library versions (known vulnerability targeting)

if ($config['debug']) {
    ini_set('display_errors', '1');
    ini_set('display_startup_errors', '1');
    error_reporting(E_ALL);
} else {
    ini_set('display_errors', '0');
    error_reporting(E_ALL);      // Still log everything, just don't display it
    ini_set('log_errors', '1');
}

// =============================================================================
// 5. Security Headers
// =============================================================================
// These HTTP response headers instruct browsers how to behave.
// They are your first line of defense against several common attacks.

// Remove "X-Powered-By: PHP/8.5.4" — don't advertise your PHP version.
// Attackers use version info to look up known vulnerabilities.
header_remove('X-Powered-By');

// Prevent MIME-type sniffing.
// Without this, a browser might execute a .txt file as JavaScript
// if it "looks" like code. This header forces the browser to trust
// the Content-Type header you declare.
header('X-Content-Type-Options: nosniff');

// Prevent the page from being embedded in an <iframe>.
// Clickjacking = attacker puts your page in a transparent iframe over
// their page, tricks user into clicking "your" button (actually theirs).
header('X-Frame-Options: SAMEORIGIN');

// Legacy XSS filter for older browsers. Modern browsers use CSP instead,
// but this costs nothing to add.
header('X-XSS-Protection: 1; mode=block');

// Control what URL is sent in the Referer header on cross-origin requests.
// 'strict-origin-when-cross-origin' = send full URL for same-origin,
// only the domain for cross-origin — prevents leaking internal URLs.
header('Referrer-Policy: strict-origin-when-cross-origin');

// =============================================================================
// 6. Database — configure (lazy connection)
// =============================================================================
// Database::configure() stores the credentials. The actual TCP connection to
// MySQL is NOT opened here — it only opens on the first Database::getInstance()
// call. This is called "lazy initialization."
//
// WHY LAZY?
// Requests that don't touch the database (a static page, a cached response)
// pay zero connection cost. A MySQL connection costs ~10-50ms.

Database::configure($config['database']);

// =============================================================================
// 7. Session — TODO: uncomment after creating src/Core/Session.php
// =============================================================================
Session::start($config['session']);



// =============================================================================
// 8. Router setup
// =============================================================================
$router = new Router();

// Middleware aliases — TODO: uncomment after creating Middleware classes
// $router->registerMiddleware('auth',  AuthMiddleware::class);
// $router->registerMiddleware('guest', GuestMiddleware::class);

// =============================================================================
// Routes
// =============================================================================
// These are temporary stub routes so you can verify the router is working.
// Each route will be replaced by a real controller method as we build the app.
//
// ROUTE SYNTAX:
//   $router->get('/path', handler)
//   $router->post('/path', handler)
//   handler = Closure OR [ControllerClass::class, 'methodName']

// Health check — always useful for confirming the app boots correctly.
// Returns JSON with app name, environment, and DB connection status.
$router->get('/health', function (array $params) use ($config): void {
    try {
        Database::getInstance();
        $dbStatus = 'connected';
    } catch (\Exception $e) {
        $dbStatus = 'error';
    }

    header('Content-Type: application/json');
    echo json_encode([
        'app'   => $config['name'],
        'env'   => $config['env'],
        'debug' => $config['debug'],
        'db'    => $dbStatus,
    ], JSON_PRETTY_PRINT);
    exit();
});


$router->get('/session-test', function (array $params): void {
    Session::set('ping', 'pong');
    Session::flash('success', 'Flash works!');
    header('Content-Type: application/json');
    echo json_encode([
        'ping'          => Session::get('ping'),
        'flash'         => Session::getFlash('success'),
        'is_logged_in'  => Session::isLoggedIn(),
        'csrf_token'    => substr(Session::csrfToken(), 0, 10) . '...',
    ], JSON_PRETTY_PRINT);
    exit();
});

// Placeholder routes — 404 until we build controllers
$router->get('/',          fn($p) => (header('Location: /health') ?: exit()));
$router->get('/login',     fn($p) => (http_response_code(200) ?: print('login page — coming soon') ?: exit()));
$router->get('/register',  fn($p) => (http_response_code(200) ?: print('register page — coming soon') ?: exit()));
$router->get('/dashboard', fn($p) => (http_response_code(200) ?: print('dashboard — coming soon') ?: exit()));

// =============================================================================
// 9. Dispatch
// =============================================================================
// parse_url strips the query string: /courses?page=2 → /courses
// REQUEST_METHOD is the HTTP verb: GET, POST, PUT, DELETE, PATCH

$uri    = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH) ?? '/';
$method = $_SERVER['REQUEST_METHOD'];

$router->dispatch($method, $uri);